'use strict';
(()=>{
  if(window.__RT76_MAP_AI_UI__)return;window.__RT76_MAP_AI_UI__=true;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=n=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}).format(Number(n)||0);
  const ownerLabel=o=>({player:'Jogador',barbarian:'Bárbara',ai:'IA',tribe:'Tribo'}[o]||o||'Outro');
  const curView=()=>String(window.currentView||'');
  const mapCard=()=>{const m=RT76.map.state(),rows=RT76.map.scan({kind:m.filter||'all',query:m.query||'',maxDistance:60}).slice(0,80);return `<section class="dashboard-card rt76-card rt76-map-card" id="rt76-map-intel"><header><div><span>RT76 • INTELIGÊNCIA DE MAPA</span><h2>Alvos, coordenadas, favoritos e inteligência</h2></div><b>${m.selected.length} selecionado(s)</b></header><form id="rt76-map-filter"><div class="rt76-map-tools"><label>Buscar<input name="query" value="${esc(m.query||'')}" placeholder="nome, dono ou 500|500"></label><label>Tipo<select name="kind"><option value="all">Todos</option>${['barbarian','ai','player'].map(x=>`<option value="${x}" ${m.filter===x?'selected':''}>${ownerLabel(x)}</option>`).join('')}</select></label><button class="btn primary">Filtrar</button><button type="button" class="btn" data-rt76-copy-coords>Copiar selecionadas</button><button type="button" class="btn secondary" data-rt76-clear-targets>Limpar</button></div></form><div class="rt76-selected-coords"><b>Coordenadas:</b> ${esc(RT76.map.selectedCoords()||'nenhuma')}</div><div class="rt76-map-list">${rows.map(v=>{const sel=m.selected.includes(v.id),fav=m.favorites.includes(v.id),intel=v.lastIntel;return `<article class="rt76-map-row ${sel?'selected':''}"><button class="rt76-target-check" data-rt76-target="${v.id}" aria-label="Selecionar ${esc(v.name)}">${sel?'✓':'+'}</button><div><b>${esc(v.name)}</b><small>${v.x}|${v.y} • ${ownerLabel(v.owner)}${v.ownerName?' • '+esc(v.ownerName):''}</small></div><span>${fmt(v.distance)} campos</span><span>${intel?`saque ${fmt(intel.lastLoot||0)} • ${Math.round((intel.fullness||0)*100)}%`:'sem intel'}</span><button class="rt76-fav" data-rt76-favorite="${v.id}" title="Favorito">${fav?'★':'☆'}</button></article>`}).join('')}</div></section>`};
  const aiCard=()=>{const a=RT76.ai?.activity?.()||[];return `<section class="dashboard-card rt76-card" id="rt76-ai-activity"><header><div><span>RT79.1 • IA OBSERVÁVEL</span><h2>Decisões reais das cidades controladas pela IA</h2></div><b>${a.length} registro(s)</b></header>${a.length?a.slice(0,30).map(x=>`<div class="queue-item"><b>${esc(x.ownerName||'IA')}</b> • ${esc((x.changes||[]).join(', '))} <small>${new Date(x.at).toLocaleTimeString('pt-BR')}</small></div>`).join(''):'<p class="muted">A atividade aparecerá quando a IA construir, recrutar, pesquisar, movimentar economia, dominar pontos ou emitir comandos.</p>'}<div class="notice info"><b>API única ativa:</b> RT76.engine.village / army / market / research / world. Interface, IA e testes passam pela mesma camada de ações.</div></section>`};
  function inject(){if(!window.RT76?.state?.())return;const p=document.querySelector('.content-panel');if(!p)return;const v=curView();if(v==='map'&&!document.querySelector('#rt76-map-intel'))p.insertAdjacentHTML('beforeend',mapCard());if(v==='systems'&&!document.querySelector('#rt76-ai-activity'))p.insertAdjacentHTML('beforeend',aiCard())}
  document.addEventListener('submit',e=>{if(e.target.id!=='rt76-map-filter')return;e.preventDefault();const f=new FormData(e.target),s=RT76.state();s.rt76.map.query=String(f.get('query')||'');s.rt76.map.filter=String(f.get('kind')||'all');RT76.save();RT76.test.render()},true);
  document.addEventListener('click',async e=>{const t=e.target.closest('[data-rt76-target]');if(t){RT76.map.toggleTarget(t.dataset.rt76Target);RT76.test.render();return}const fav=e.target.closest('[data-rt76-favorite]');if(fav){RT76.map.toggleFavorite(fav.dataset.rt76Favorite);RT76.test.render();return}if(e.target.closest('[data-rt76-clear-targets]')){RT76.map.clear();RT76.test.render();return}if(e.target.closest('[data-rt76-copy-coords]')){const txt=RT76.map.selectedCoords();if(!txt){alert('Nenhuma coordenada selecionada.');return}try{await navigator.clipboard.writeText(txt)}catch(_){const ta=document.createElement('textarea');ta.value=txt;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}}},true);
  const st=document.createElement('style');st.textContent=`.rt76-map-tools{display:grid;grid-template-columns:minmax(220px,1fr) 160px auto auto auto;gap:8px;align-items:end}.rt76-map-tools input,.rt76-map-tools select{width:100%;padding:8px;background:#10150f;color:#eadfbd;border:1px solid #735c2b}.rt76-selected-coords{margin:10px 0;padding:9px;border:1px solid #735c2b;background:#0e120d;word-break:break-word}.rt76-map-list{display:grid;gap:4px;max-height:620px;overflow:auto}.rt76-map-row{display:grid;grid-template-columns:38px minmax(220px,1fr) 110px minmax(150px,.7fr) 38px;gap:8px;align-items:center;padding:8px;border:1px solid #3f432e;background:#121711}.rt76-map-row.selected{border-color:#d4ad4d;background:#24200f}.rt76-map-row small{display:block;opacity:.72}.rt76-target-check,.rt76-fav{height:30px;border:1px solid #735c2b;background:#1b2118;color:#e2bd62;font-weight:800}.rt76-fav{font-size:1.1rem}@media(max-width:780px){.rt76-map-tools{grid-template-columns:1fr 1fr}.rt76-map-row{grid-template-columns:34px minmax(0,1fr) 34px}.rt76-map-row>span{grid-column:2}.rt76-map-tools .btn{width:100%}}`;document.head.appendChild(st);
  new MutationObserver(()=>queueMicrotask(inject)).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});inject();
})();

/* RT79.1: a IA também pesquisa. A pesquisa custa recursos e segue o perfil da cidade. */
(()=>{
  if(window.__RT79_AI_RESEARCH__)return;window.__RT79_AI_RESEARCH__=true;
  const plans={raider:['axe','light','ram','spear','spy'],warden:['spear','sword','archer','heavy'],expander:['axe','light','ram','catapult','heavy'],opportunist:['spy','light','archer','axe','spear']};
  function tick(){const s=window.RT76?.state?.();if(!s?.villages)return false;s.rt76||={};const now=Date.now(),diff=String(s.settings?.difficulty||'normal'),cadence=diff==='hard'?45000:diff==='easy'?105000:70000;if(Number(s.rt76.aiResearchNextAt||0)>now)return false;s.rt76.aiResearchNextAt=now+cadence;let changed=false;for(const v of Object.values(s.villages).filter(v=>v.owner==='ai')){if(Number(v.buildings?.smith||0)<1)continue;v.unitResearch||={};const personality=window.aiPersonality?.(v)||'opportunist',order=plans[personality]||plans.opportunist;for(const key of order){if(!window.D?.units?.[key])continue;const level=Math.max(0,Number(v.unitResearch[key]||0));if(level>=3)continue;const factor=level+1,cost={wood:Math.round(420*factor),clay:Math.round(340*factor),iron:Math.round(520*factor)},r=v.resources||{};if(Number(r.wood||0)<cost.wood||Number(r.clay||0)<cost.clay||Number(r.iron||0)<cost.iron)continue;r.wood-=cost.wood;r.clay-=cost.clay;r.iron-=cost.iron;v.unitResearch[key]=level+1;s.rt76.aiActivity||=[];s.rt76.aiActivity.unshift({at:now,villageId:v.id,ownerName:v.ownerName||'IA',changes:['RESEARCH'],research:key,level:level+1,personality});s.rt76.aiActivity=s.rt76.aiActivity.slice(0,150);changed=true;break}}if(changed)window.RT76?.save?.();return changed}
  window.RT79_AI_RESEARCH={tick};setInterval(tick,10000);
})();
