const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8'};
const SB=Deno.env.get('SUPABASE_URL')||'',SK=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const out=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:C});
const num=v=>Math.max(0,Math.floor(Number(v)||0));
function user(req){const a=req.headers.get('authorization')||'',t=a.replace(/^Bearer\s+/i,''),p=t.split('.')[1]||'';if(!p)return null;try{return JSON.parse(atob(p.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(p.length/4)*4,'=')))}catch{return null}}
async function db(path){const r=await fetch(`${SB}/rest/v1/${path}`,{headers:{apikey:SK,Authorization:`Bearer ${SK}`}}),t=await r.text();let d=null;if(t)try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.hint||String(d||r.status));return d}
async function access(uid,wid){const [w,p,a]=await Promise.all([db(`worlds?id=eq.${wid}&select=id,is_active,status&limit=1`),db(`player_worlds?world_id=eq.${wid}&user_id=eq.${uid}&select=id,is_suspended&limit=1`),db(`rt_admin_auth_users?user_id=eq.${uid}&active=eq.true&select=user_id&limit=1`)]);if(a?.length)throw new Error('Conta administrativa não pode jogar.');if(!w?.[0]||!w[0].is_active||String(w[0].status||'open')!=='open')throw new Error('Mundo fechado.');if(!p?.length||p[0].is_suspended)throw new Error('Entre no mundo antes de jogar.')}
function publicBuildings(points){const p=num(points),s=p<300?1:p<700?3:p<1500?5:p<3500?8:p<8000?11:p<16000?14:p<32000?18:22,z=(d,min=0)=>Math.max(min,Math.min(30,s-d));return {main:s,barracks:z(1,1),stable:z(4),garage:z(7),smith:z(3),rally:1,market:z(3),timber:z(1,1),clay:z(1,1),iron:z(1,1),farm:z(1,1),warehouse:z(2,1),hide:z(8),wall:z(5),academy:z(9),statue:s>=5?1:0,watchtower:z(10),church:0,first_church:0}}
function publicVillage(v){return {id:v.id,owner_user_id:v.owner_user_id,owner_kind:v.owner_kind,owner_name:v.owner_name,tribe_name:v.tribe_name,name:v.name,x:v.x,y:v.y,points:num(v.points),buildings:publicBuildings(v.points),updated_at:v.updated_at,public_visual_projection:true}}
function incoming(target,c){const lvl=num(target?.buildings?.watchtower),real=c.troops&&typeof c.troops==='object'?c.troops:{},total=Object.values(real).reduce((a,b)=>a+num(b),0),noble=num(real.noble)>0,siege=num(real.ram)+num(real.catapult)>0,spy=num(real.spy)>0;let troops={},visible=null,visibility='unknown',klass='unknown',approx=false;if(lvl>=1&&lvl<5){visible=Math.max(1,Math.round(total/25)*25);troops={spear:visible};visibility='approximate';klass='hostile';approx=true}else if(lvl>=5&&lvl<10){visible=total;troops={spear:total};visibility='quantity';klass='attack'}else if(lvl>=10&&lvl<15){visible=total;const f=(noble?1:0)+(siege?1:0);troops={spear:Math.max(0,total-f)};if(siege)troops.ram=1;if(noble)troops.noble=1;visibility='tactical';klass=noble?'noble':siege?'siege':spy&&total<=num(real.spy)+2?'spy':total<=10?'fake_likely':'attack'}else if(lvl>=15){visible=total;troops=real;visibility='composition';klass=noble?'noble':siege?'siege':spy&&total<=num(real.spy)+2?'spy':total<=10?'fake_likely':'attack'}const urgency=new Date(c.arrives_at).getTime()<Date.now()+600000?20:0,risk=Math.min(100,Math.max(1,20+urgency+(visible==null?0:Math.min(50,visible/20))+(lvl>=10&&noble?25:0)+(lvl>=10&&siege?15:0)));return {...c,troops,payload:lvl>=15?(c.payload||{}):{travel_ms:num(c.payload?.travel_ms)},rt81_intel:{watchtower_level:lvl,visibility,total_units:visible,approximate:approx,class:klass,siege_detected:lvl>=10?siege:null,noble_detected:lvl>=10?noble:null,risk:Math.round(risk)}}}
async function poll(u,wid){await access(u.sub,wid);const own=await db(`villages?world_id=eq.${wid}&owner_user_id=eq.${u.sub}&select=*`),world=await db(`villages?world_id=eq.${wid}&select=id,owner_user_id,owner_kind,owner_name,tribe_name,name,x,y,points,updated_at&order=points.desc&limit=2000`),ids=(own||[]).map(v=>v.id),ownMap=new Map((own||[]).map(v=>[String(v.id),v]));let commands=[];if(ids.length)commands=await db(`commands?world_id=eq.${wid}&or=(owner_user_id.eq.${u.sub},target_village_id.in.(${ids.join(',')}))&select=*&order=started_at.desc&limit=80`);commands=(commands||[]).map(c=>String(c.owner_user_id)===u.sub?c:ownMap.has(String(c.target_village_id))?incoming(ownMap.get(String(c.target_village_id)),c):null).filter(Boolean);const reports=await db(`reports?world_id=eq.${wid}&user_id=eq.${u.sub}&select=*&order=created_at.desc&limit=30`);return {version:81,security_revision:'rt81',own_villages:own||[],world_villages:(world||[]).map(publicVillage),commands,reports:reports||[]}}
async function proxy(req,body){const r=await fetch(`${SB}/functions/v1/rt-multiplayer-v59`,{method:'POST',headers:{apikey:req.headers.get('apikey')||'',Authorization:req.headers.get('authorization')||'','Content-Type':'application/json'},body:JSON.stringify(body)}),text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}return new Response(typeof data==='string'?data:JSON.stringify(data),{status:r.status,headers:C})}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return out({error:'Método inválido.'},405);const u=user(req);if(!u?.sub)return out({error:'Sessão inválida.'},401);try{const body=await req.json(),wid=String(body.world_id||''),action=String(body.action||'');if(!wid)throw new Error('world_id ausente.');if(action==='poll')return out(await poll(u,wid));return await proxy(req,body)}catch(e){console.error(e);return out({error:e?.message||String(e)},400)}});
