const qs=(s,r=document)=>r.querySelector(s),qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}),number=new Intl.NumberFormat('pt-BR'),dateTime=new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short'});
let tokenValue=null,state=null,build=null,currentView='inicio';
const viewMeta={inicio:['VISÃO GERAL','Sua vida continua aqui.'],personagem:['PERSONAGEM','Quem você é neste mundo.'],mundo:['MUNDO VIVO','A sociedade continua mesmo quando você sai.'],economia:['ECONOMIA','Empresas, trabalho e mercado.'],governo:['GOVERNO','Políticas, serviços e tributação.'],financas:['FINANÇAS','Seu dinheiro faz parte do mundo.'],auditoria:['INTEGRIDADE','O mundo precisa fechar as contas.']};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const fmt=v=>number.format(n(v));
const row=(label,value,small='')=>`<div class="row"><div><span>${esc(label)}</span>${small?`<small>${esc(small)}</small>`:''}</div><strong>${value}</strong></div>`;
const metric=(label,value,small='')=>`<article class="metric"><span>${esc(label)}</span><strong>${value}</strong>${small?`<small>${esc(small)}</small>`:''}</article>`;
function status(text,type=''){const el=qs('#globalStatus');if(!el)return;el.textContent=text;el.className='global-status'+(type?` ${type}`:'');}
function authStatus(text){qs('#authStatus').textContent=text||'';}
async function jsonFetch(url,opt={}){const r=await fetch(url,{credentials:'include',cache:'no-store',...opt,headers:{accept:'application/json',...(opt.body?{'content-type':'application/json'}:{}),...(opt.headers||{})}});let d=null;try{d=await r.json()}catch{d={ok:false,error:{message:`HTTP ${r.status}`}}}if(!r.ok||d?.ok===false)throw new Error(d?.error?.message||d?.message||`HTTP ${r.status}`);return d;}
async function resolveToken(){const d=await jsonFetch('/api/auth/token');const t=d.token||d.access_token||d.session?.token;if(!t)throw new Error('AUTH_REQUIRED');tokenValue=t;return t;}
async function deep(path,opt={}){const t=tokenValue||await resolveToken();return jsonFetch(`/api/deep/${path}`,{...opt,headers:{authorization:`Bearer ${t}`,...(opt.headers||{})}});}
async function action(action,payload={}){status(`Executando ${action}...`);const out=await deep('action',{method:'POST',headers:{'idempotency-key':crypto.randomUUID()},body:JSON.stringify({action,...payload})});state=out.state;render();status('Estado salvo e sincronizado.','ok');return out;}
function showAuth(){qs('#authScreen').hidden=false;qs('#shell').hidden=true;}
function showShell(){qs('#authScreen').hidden=true;qs('#shell').hidden=false;}
function switchView(name){currentView=name;qsa('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));qsa('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));const [k,t]=viewMeta[name]||viewMeta.inicio;qs('#viewKicker').textContent=k;qs('#viewTitle').textContent=t;document.querySelector('.shell')?.classList.remove('menu-open');history.replaceState(null,'',`#${name}`);}
function player(){return state?.compact?.player||{};}
function fat(){return state?.financial_and_tax||state?.compact?.financial_and_tax||{};}
function macro(){return fat().macro||{};}
function render(){if(!state)return;const p=player(),f=fat(),m=macro(),eco=state.economy||{},gov=state.government||{},env=state.environment||{},infra=state.infrastructure||{},audit=state.audit||{};
  qs('#worldClock').textContent=state.world_time?dateTime.format(new Date(state.world_time)):'—';qs('#versionBadge').textContent=state.site_version||'V19.8';
  qs('#worldNow').innerHTML=row('Tempo do mundo',state.world_time?dateTime.format(new Date(state.world_time)):'—')+row('Escala',`${state.world_scale||20}×`)+row('Persistência',state.snapshot_collection||'—')+row('Integridade',audit.ok?'<span class="good">PASS</span>':'<span class="bad-text">FAIL</span>');
  qs('#summaryCards').innerHTML=metric('Dinheiro',money.format(n(state.finance?.cash)),`Banco ${money.format(n(state.finance?.bank))}`)+metric('NPCs',fmt(state.counts?.npcs),'sociedade persistente')+metric('Empresas',fmt(state.counts?.companies),`${fmt(eco.companies_active)} ativas`)+metric('Crédito',fmt(f.credit_score??p.credit_score),'score pessoal')+metric('Receita fiscal',money.format(n(m.tax_revenue)),'tesouro simulado')+metric('Ledger Δ',String(audit.total_delta??'?'),audit.unbalanced_batches===0?'balanceado':'verificar');
  qs('#homePlayer').innerHTML=row('Local',p.location_id||'—')+row('Saúde',`${fmt(p.health)} / 100`)+row('Energia',`${fmt(p.energy)} / 100`)+row('Reputação',fmt(p.reputation))+row('Regime fiscal',f.tax_profile?.regime||'—');
  qs('#homeWorld').innerHTML=row('População simulada',fmt(m.br_population||221000000))+row('Serviços públicos',`${fmt(infra.services_online)} / ${fmt(infra.services_total)}`)+row('Desastres registrados',fmt(env.disasters?.length))+row('Quintis de demanda',(m.demand_by_quintile||[]).join(' · '));
  qs('#characterId').textContent=p.character_id||'—';qs('#playerStats').innerHTML=metric('Caixa',money.format(n(p.cash)))+metric('Banco',money.format(n(p.bank)))+metric('Saúde',fmt(p.health))+metric('Energia',fmt(p.energy))+metric('Humor',fmt(p.mood))+metric('Fome',fmt(p.hunger))+metric('Reputação',fmt(p.reputation))+metric('Crédito',fmt(p.credit_score));
  qs('#conditionRows').innerHTML=row('Saúde',`${fmt(p.health)} / 100`)+row('Energia',`${fmt(p.energy)} / 100`)+row('Humor',`${fmt(p.mood)} / 100`)+row('Fome',fmt(p.hunger))+row('Condições médicas',fmt(p.health_record?.conditions?.length));
  qs('#careerRows').innerHTML=row('Emprego',p.employment||'Sem vínculo')+row('Local',p.location_id||'—')+row('Reputação',fmt(p.reputation))+row('Educação',`${Object.keys(p.education?.skills||{}).length} competências`)+row('Propriedades',fmt(p.properties?.length));
  qs('#worldMetrics').innerHTML=metric('População BR',fmt(m.br_population||221000000))+metric('Dias macro',fmt(m.days_processed))+metric('Liquidez',String(m.liquidity??state.finance?.fx?.liquidity??'—'))+metric('Turismo',String(m.tourism_index??'—'))+metric('Balança',String(m.trade_balance??'—'))+metric('Prêmio paralelo',String(m.parallel_premium??'—'));
  qs('#macroRows').innerHTML=row('Quintis de demanda',(m.demand_by_quintile||[]).join(' · '))+row('Inflação',String(state.finance?.fx?.inflation??state.compact?.fx?.inflation??'—'))+row('Juros básicos',String(state.finance?.fx?.policy_rate??state.compact?.fx?.policy_rate??'—'))+row('Receita tributária',money.format(n(m.tax_revenue)))+row('Último ciclo',m.last_cycle_world?dateTime.format(new Date(m.last_cycle_world)):'—');
  qs('#environmentRows').innerHTML=row('Clima',typeof env.weather==='string'?env.weather:JSON.stringify(env.weather||{}))+row('Poluição',String(env.pollution_index??'—'))+row('Emissões',String(env.emissions??'—'))+row('Desastres',fmt(env.disasters?.length));
  qs('#autonomyRows').innerHTML=row('Escala temporal',`${state.world_scale||20}×`)+row('Catch-up por usuário','ATIVO')+row('Persistência segmentada',state.persistence_compat||'—')+row('CAS / idempotência','ATIVOS');
  qs('#economyMetrics').innerHTML=metric('Empresas',fmt(eco.companies_total))+metric('Ativas',fmt(eco.companies_active))+metric('Falidas',fmt(eco.companies_bankrupt))+metric('Pedidos',fmt(eco.purchase_orders))+metric('Remessas',fmt(eco.shipments))+metric('Negócios',fmt(eco.market_trades));
  const companies=(eco.companies||[]).slice(0,80);qs('#companyCount').textContent=`${fmt(eco.companies_total)} empresas`;qs('#companyTable').innerHTML=companies.map(c=>`<tr><td>${esc(c.name||c.company_id)}</td><td>${esc(c.sector||c.industry||'—')}</td><td>${esc(c.status||'—')}</td><td>${money.format(n(c.cash))}</td><td>${fmt(c.employees?.length??c.employees_count)}</td></tr>`).join('')||'<tr><td colspan="5">Sem empresas disponíveis.</td></tr>';
  const policies=gov.policies||{};qs('#policyRows').innerHTML=Object.keys(policies).length?Object.entries(policies).slice(0,20).map(([k,v])=>row(k,typeof v==='object'?esc(JSON.stringify(v)):esc(v))).join(''):row('Políticas','Nenhum dado');
  qs('#infraRows').innerHTML=row('Serviços online',fmt(infra.services_online))+row('Serviços totais',fmt(infra.services_total))+row('Indisponibilidades',fmt(infra.outages?.length));
  qs('#taxGovernmentRows').innerHTML=row('Regimes','MEI · SIMPLES · PRESUMIDO · REAL')+row('Registros fiscais',fmt(f.tax_record_count))+row('Pagamentos empresariais',fmt(f.enterprise_tax_paid))+row('Calendário',`${fmt(f.tax_calendar?.length)} obrigações`)+row('Risco de financiamento',f.financing_restricted?'<span class="bad-text">RESTRITO</span>':'<span class="good">LIBERADO</span>');
  qs('#financeMetrics').innerHTML=metric('Caixa',money.format(n(state.finance?.cash)))+metric('Banco',money.format(n(state.finance?.bank)))+metric('Empréstimos',fmt(state.finance?.loans?.length))+metric('Cartões',fmt(f.cards?.length))+metric('Investimentos',fmt(f.investments?.length))+metric('Impostos',fmt(f.tax_record_count));
  qs('#taxRegime').value=f.tax_profile?.regime||'MEI';qs('#taxRows').innerHTML=(f.tax_notices||[]).slice(-10).map(x=>row(`${x.tax_code} · ${x.status}`,money.format(n(x.balance)),`vence ${x.due_world?new Date(x.due_world).toLocaleDateString('pt-BR'):'—'} · atraso ${x.days_late||0}d`)).join('')||row('Impostos','Nenhum lançamento');
  qs('#cardRows').innerHTML=(f.cards||[]).map(c=>row(c.issuer||'Cartão',`${money.format(n(c.balance))} / ${money.format(n(c.limit))}`,`${c.statement?.length||0} compras · juros ${money.format(n(c.interest_accrued))}`)).join('')||row('Cartões','Nenhum cartão');
  qs('#investmentRows').innerHTML=(f.investments||[]).map(i=>row(i.instrument||'Ativo',money.format(n(i.value)),`rendimento ${money.format(n(i.yield_accrued))}`)).join('')||row('Investimentos','Nenhuma aplicação');
  qs('#insuranceRows').innerHTML=(f.insurance_policies||[]).map(i=>row(`${i.type} · ${i.status}`,money.format(n(i.coverage)),`prêmio ${money.format(n(i.premium))}`)).join('')||row('Seguros','Nenhuma apólice');
  const ok=!!audit.ok;qs('#auditMark').textContent=ok?'✓':'!';qs('#auditMark').classList.toggle('bad',!ok);qs('#auditTitle').textContent=ok?'Mundo consistente.':'Falha de integridade detectada.';qs('#auditText').textContent=`Ledger Δ ${audit.total_delta??'?'} · ${audit.unbalanced_batches??'?'} batches desbalanceados · ${audit.orphan_shipments??'?'} remessas órfãs.`;
  qs('#auditMetrics').innerHTML=metric('Ledger Δ',String(audit.total_delta??'?'))+metric('Batches inválidos',fmt(audit.unbalanced_batches))+metric('Remessas órfãs',fmt(audit.orphan_shipments))+metric('Estoque negativo',fmt(audit.negative_inventory))+metric('NPC divergentes',fmt(audit.npc_agent_mismatches))+metric('Empresas divergentes',fmt(audit.company_agent_mismatches));
  qs('#buildRows').innerHTML=row('Site',state.site_version||'—')+row('Engine',state.engine_version||'—')+row('Persistência',state.persistence_compat||'—')+row('Store version',String(state.store_version??'—'))+(build?row('Escopo',build.scope||'—')+row('Handler SHA',build.handler_sha?.slice(0,20)+'…'):'' );
}
async function loadWorld(){status('Carregando seu mundo persistente...');state=await deep('state');try{build=await jsonFetch('/final-build.json')}catch{}render();showShell();switchView(location.hash.replace('#','')||'inicio');status('Mundo carregado.','ok');}
async function boot(){try{await resolveToken();await loadWorld()}catch(e){if(/AUTH|401|unauth/i.test(String(e.message)))showAuth();else{showAuth();authStatus(`Não foi possível iniciar: ${e.message}`)}}}
qsa('[data-auth-tab]').forEach(b=>b.addEventListener('click',()=>{qsa('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===b));qs('#loginForm').hidden=b.dataset.authTab!=='login';qs('#signupForm').hidden=b.dataset.authTab!=='signup';authStatus('')}));
qs('#loginForm').addEventListener('submit',async e=>{e.preventDefault();authStatus('Entrando...');try{await jsonFetch('/api/auth/sign-in/email',{method:'POST',body:JSON.stringify({email:qs('#loginEmail').value.trim(),password:qs('#loginPassword').value})});await resolveToken();await loadWorld()}catch(err){authStatus(err.message)}});
qs('#signupForm').addEventListener('submit',async e=>{e.preventDefault();authStatus('Criando conta...');try{await jsonFetch('/api/auth/sign-up/email',{method:'POST',body:JSON.stringify({name:qs('#signupName').value.trim(),email:qs('#signupEmail').value.trim(),password:qs('#signupPassword').value})});await resolveToken();await loadWorld()}catch(err){authStatus(err.message)}});
qsa('[data-nav]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();switchView(b.dataset.nav)}));qsa('[data-go]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.go)));qs('#menuBtn').addEventListener('click',()=>qs('.shell').classList.toggle('menu-open'));
qs('#logoutBtn').addEventListener('click',async()=>{try{await jsonFetch('/api/auth/sign-out',{method:'POST'})}catch{}tokenValue=null;state=null;showAuth();authStatus('Sessão encerrada.')} );
for(const b of qsa('[data-action]'))b.addEventListener('click',()=>action(b.dataset.action,{amount:n(qs('#quickAmount').value)}).catch(e=>status(e.message,'bad')));
const catchup=async()=>{status('Sincronizando tempo do mundo...');try{state=await deep('catchup',{method:'POST',headers:{'idempotency-key':crypto.randomUUID()},body:'{}'});render();status('Catch-up concluído.','ok')}catch(e){status(e.message,'bad')}};qs('#catchupHome').onclick=catchup;qs('#catchupWorld').onclick=catchup;
qs('#changeTaxRegime').onclick=()=>action('change_tax_regime',{regime:qs('#taxRegime').value}).catch(e=>status(e.message,'bad'));
qs('#payOpenTax').onclick=()=>{const p=player(),notice=(fat().tax_notices||[]).find(x=>x.owner_id===p.character_id&&x.status==='OPEN');if(!notice)return status('Não há imposto pessoal aberto.','bad');action('pay_official_tax',{notice_id:notice.notice_id}).catch(e=>status(e.message,'bad'))};
qs('#buyCard').onclick=()=>action('card_purchase',{amount:n(qs('#cardAmount').value),merchant:'Mercado Bacathegas',installments:Math.max(1,n(qs('#cardInstallments').value)),limit:3000}).catch(e=>status(e.message,'bad'));
qs('#payCard').onclick=()=>{const c=fat().cards?.find(x=>x.status==='ACTIVE');if(!c)return status('Você ainda não possui cartão ativo.','bad');action('pay_card_bill',{card_id:c.card_id,amount:100}).catch(e=>status(e.message,'bad'))};
qs('#investBtn').onclick=()=>action('invest',{amount:n(qs('#investAmount').value),instrument:'BOND',annual_yield:.08}).catch(e=>status(e.message,'bad'));
qs('#redeemBtn').onclick=()=>{const i=fat().investments?.find(x=>x.status==='ACTIVE');if(!i)return status('Nenhum investimento ativo.','bad');action('redeem_investment',{investment_id:i.investment_id,amount:100}).catch(e=>status(e.message,'bad'))};
qs('#insuranceBtn').onclick=()=>action('buy_insurance',{type:'PROPERTY',premium:30,coverage:1000,deductible:100}).catch(e=>status(e.message,'bad'));
qs('#claimBtn').onclick=()=>{const p=fat().insurance_policies?.find(x=>x.status==='ACTIVE');if(!p)return status('Nenhuma apólice ativa.','bad');action('file_insurance_claim',{policy_id:p.policy_id,loss:500}).catch(e=>status(e.message,'bad'))};
window.addEventListener('hashchange',()=>switchView(location.hash.replace('#','')||'inicio'));boot();
