from pathlib import Path
from playwright.sync_api import sync_playwright
import json,time
BASE='http://127.0.0.1:8765/index.html?rt76master=1'
OUT=Path('RT76_MASTER_CONTRACT_E2E');OUT.mkdir(exist_ok=True)
R={'checks':{},'failures':[],'page_errors':[],'console_errors':[],'started_at':time.time()}
def ck(k,v,d=''):
 R['checks'][k]=bool(v)
 if not v:R['failures'].append({'check':k,'detail':str(d)[:1600]})
def start(p):
 p.goto(BASE,wait_until='domcontentloaded',timeout=45000);p.wait_for_timeout(700)
 x=p.locator('[data-play-offline]').first
 if x.count() and x.is_visible():x.click();p.wait_for_timeout(400)
 f=p.locator('#start-form')
 if f.count() and f.is_visible():
  f.locator('[name=playerName]').fill('Contrato Mestre RT76');f.locator('[name=villageName]').fill('Aldeia Contrato Mestre');f.locator('button[type=submit],button:not([type])').last.click()
 p.wait_for_selector('.game-shell',timeout=20000);p.wait_for_function('window.RT76&&RT76.master&&window.__RT76_MASTER_PLAN__===true',timeout=20000);p.wait_for_timeout(400)
def view(p,v):p.evaluate('(x)=>RT76.test.setView(x)',v);p.wait_for_timeout(300)
def shot(p,n):p.screenshot(path=str(OUT/n),full_page=True)
def run(p):
 start(p)
 meta=p.evaluate('''()=>({master:!!RT76.master,rt:!!window.RT,api:[typeof RT?.village?.build,typeof RT?.army?.recruit,typeof RT?.army?.attack,typeof RT?.market?.send,typeof RT?.research?.start,typeof RT?.world?.scan]})''');ck('contract.master_runtime',meta['master'] and meta['rt'],meta);ck('contract.RT_api',all(x=='function' for x in meta['api']),meta)
 wave=p.evaluate('''()=>{const s=RT76.state(),v=RT76.test.getActiveVillage();v.units.spear=Math.max(v.units.spear||0,200);v.buildings.rally=Math.max(v.buildings.rally||0,20);const t=Object.values(s.villages).find(x=>x.owner==='barbarian'),before=s.rt76.scheduledCommands.length,arr=Date.now()+3600000;const out=RT76.master.planner.planWave({sourceId:v.id,targetId:t.id,troops:{spear:5},arrivalAt:arr,count:3,gapMs:1250,kind:'fake'}),rows=s.rt76.scheduledCommands.slice(before);return {count:out.length,added:rows.length,kinds:rows.map(x=>x.kind),arrivals:rows.map(x=>x.arrivalAt)}}''');ck('planner.wave',wave['count']==3 and wave['added']==3 and wave['kinds']==['fake']*3,wave);ck('planner.gap',wave['arrivals'][1]-wave['arrivals'][0]==1250 and wave['arrivals'][2]-wave['arrivals'][1]==1250,wave)
 recall=p.evaluate('''()=>{const s=RT76.state(),v=RT76.test.getActiveVillage(),t=Object.values(s.villages).find(x=>x.owner==='barbarian');v.units.spear=Math.max(v.units.spear||0,100);const before=s.commands.length;RT76.test.sendAttack(t.id,{spear:4},{attackType:'normal'});const c=s.commands.slice(before).find(x=>x.kind==='attack'&&x.phase==='outbound'),x=RT76.master.planner.recall(c.id);return {phase:x.phase,targetId:x.targetId,source:v.id}}''');ck('planner.recall',recall['phase']=='return' and recall['targetId']==recall['source'],recall)
 support=p.evaluate('''()=>{const s=RT76.state(),a=RT76.test.getActiveVillage(),b=Object.values(s.villages).find(x=>x.id!==a.id&&!x._onlineRemote);b.owner='player';b.ownerName=s.player.name;a.units.spear=Math.max(a.units.spear||0,80);const x=RT76.master.planner.scheduleSupport({sourceId:a.id,targetId:b.id,troops:{spear:7},arrivalAt:Date.now()+3600000}),m=s.rt76.master.scheduledSupport.find(y=>y.id===x.id);m.departAt=Date.now()-1;const before=s.commands.length;RT76.master.planner.processSupport(Date.now());const c=s.commands.slice(before).find(y=>y.kind==='support');return {status:m.status,cmd:!!c,q:c?.troops?.spear||0}}''');ck('planner.support',support['status']=='sent' and support['cmd'] and support['q']==7,support)
 farm=p.evaluate('''()=>{const s=RT76.state(),bars=Object.values(s.villages).filter(x=>x.owner==='barbarian').slice(0,2);RT76.master.farm.setRules({maxDistance:100,maxWall:5,maxLossPct:20,reattackMinutes:0,cycleLimit:2});if(bars[0])s.rt76.targetIntel[bars[0].id]={wall:3,lossPct:10,lastVisit:0,visits:1,fullness:.5};if(bars[1])s.rt76.targetIntel[bars[1].id]={wall:12,lossPct:0,lastVisit:0,visits:1,fullness:.5};const c=RT76.master.farm.candidates();return {r:RT76.master.farm.rules(),ids:c.map(x=>x.id),good:bars[0]?.id,bad:bars[1]?.id}}''');ck('farm.rules',farm['r']['maxWall']==5 and farm['r']['maxLossPct']==20,farm);ck('farm.filter',farm['good'] in farm['ids'] and farm['bad'] not in farm['ids'],farm)
 intel=p.evaluate('''()=>{const s=RT76.state(),t=Object.values(s.villages).find(x=>x.owner!=='player');RT76.master.intel.observe(t.id);t.points=(t.points||0)+123;const b=RT76.master.intel.observe(t.id),h=RT76.master.intel.history(t.id),c=RT76.master.intel.classify(t.id);return {len:h.length,delta:b.pointDelta,growing:c.growing}}''');ck('intel.history',intel['len']>=2 and intel['delta']==123 and intel['growing'],intel)
 inc=p.evaluate('''()=>{const s=RT76.state(),d=RT76.test.getActiveVillage(),a=Object.values(s.villages).find(x=>x.id!==d.id&&x.owner!=='player');if(!a)return {missingSource:true};d.buildings.watchtower=20;return RT76.master.intel.incoming({id:'i',kind:'attack',phase:'outbound',sourceId:a.id,targetId:d.id,troops:{spear:300,ram:12},attackType:'normal',arriveAt:Date.now()+60000})}''');ck('intel.watchtower',not inc.get('missingSource') and inc['origin']!='?' and inc['type']=='Ataque' and inc['exactTroops']['spear']==300,inc)
 market=p.evaluate('''()=>{const s=RT76.state(),a=RT76.test.getActiveVillage(),b=Object.values(s.villages).find(x=>x.id!==a.id&&!x._onlineRemote);b.owner='player';b.ownerName=s.player.name;a.buildings.market=20;b.buildings.market=20;a.resources.wood=100000;b.resources.wood=0;RT76.master.market.addRoute({sourceId:a.id,targetId:b.id,resource:'wood',amount:2500,minSource:5000,intervalMs:60000});const before=s.commands.length,n=RT76.master.market.runRoutes(Date.now()+120000),cmd=s.commands.slice(before).find(x=>x.kind==='trade');RT76.master.market.request({targetId:b.id,resource:'clay',amount:1000});a.resources.clay=100000;const f=RT76.master.market.fulfillRequests(5);return {n,cmd:!!cmd,f}}''');ck('market.route',market['n']>=1 and market['cmd'],market);ck('market.request',market['f']>=1,market)
 jobs=p.evaluate('''()=>{const s=RT76.state(),a=RT76.test.getActiveVillage(),b=Object.values(s.villages).find(x=>x.id!==a.id&&x.owner==='player');a.resources.iron=100000;a.buildings.market=20;b.buildings.market=20;const j=RT76.master.jobs.enqueue('TRADE',{sourceId:a.id,targetId:b.id,resources:{iron:333}},Date.now()-1),n=RT76.master.jobs.process(Date.now(),10),row=RT76.master.jobs.list().find(x=>x.id===j.id);return {n,status:row.status}}''');ck('jobs.execute',jobs['n']>=1 and jobs['status']=='done',jobs)
 ai=p.evaluate('''()=>{const s=RT76.state();s.rt76.master.aiJobs=[];const n=RT76.master.ai.planJobs(Date.now()),profiles=Object.keys(RT76.master.ai.profiles);return {n,profiles,planned:s.rt76.master.aiJobs.filter(x=>x.status==='planned').length}}''');ck('ai.profiles',set(ai['profiles'])=={'raider','warden','expander','opportunist'},ai);ck('ai.jobs',ai['n']>0 and ai['planned']>0,ai)
 gov=p.evaluate('''()=>{const v=RT76.test.getActiveVillage();RT76.master.governor.setRole(v.id,'defensive');return {role:RT76.master.governor.role(v.id),profiles:Object.keys(RT76.master.governor.profiles)}}''');ck('governor',gov['role']=='defensive' and len(gov['profiles'])==4,gov)
 tribe=p.evaluate('''()=>{const s=RT76.state();s.player.tribe='Contrato';s.player.tribeData={name:'Contrato',level:1,xp:0,treasury:{wood:50000,clay:50000,iron:50000},totalDonated:0,technologies:{economy:0,logistics:0,war:0,command:0,fellowship:0},diplomacy:{pacts:[],allies:[],enemies:[]},rights:{duke:true,baron:true,invite:true,diplomacy:true,circularMail:true,forumMod:true,hiddenForums:true,trustedForums:true},forum:[],claimedObjectives:[],supportRequests:[],wall:[]};const p=RT76.master.tribeProjects.create('roads'),x=RT76.master.tribeProjects.contribute(p.id,{wood:15000,clay:10000,iron:5000});return {status:x.status,rank:RT76.master.tribeProjects.ranking().length}}''');ck('tribe.project',tribe['status']=='complete' and tribe['rank']>=1,tribe)
 for name,sel in [('rally','#rt76-master-planner'),('market','#rt76-master-logistics'),('manager','#rt76-master-governor'),('systems','#rt76-master-engine'),('map','#rt76-master-intel'),('tribe','#rt76-master-tribe')]:view(p,name);ck('ui.'+name,p.locator(sel).count()==1,p.locator(sel).count());shot(p,'desktop-'+name+'.png')
 view(p,'map');cell=p.locator('.map-cell[data-target],.rt22-map-cell[data-target]').first
 if cell.count():cell.dispatch_event('contextmenu',{'clientX':250,'clientY':200});p.wait_for_timeout(100)
 ck('map.context',p.locator('#rt76-map-context').count()==1,p.locator('#rt76-map-context').count())
 p.evaluate('''()=>{const v=RT76.test.getActiveVillage();RT76.master.governor.setRole(v.id,'military');RT76.master.farm.setRules({maxDistance:77});RT76.save()}''');p.reload(wait_until='domcontentloaded');p.wait_for_timeout(500);x=p.locator('[data-play-offline]').first
 if x.count() and x.is_visible():x.click();p.wait_for_timeout(400)
 p.wait_for_function('window.RT76&&RT76.master&&RT76.state()');pers=p.evaluate('''()=>({d:RT76.master.farm.rules().maxDistance,roles:Object.values(RT76.master.ensure().villageRoles)})''');ck('save.master',pers['d']==77 and 'military' in pers['roles'],pers)
 p.set_viewport_size({'width':390,'height':844})
 for name,sel in [('rally','#rt76-master-planner'),('market','#rt76-master-logistics'),('manager','#rt76-master-governor'),('systems','#rt76-master-engine'),('map','#rt76-master-intel')]:view(p,name);ck('mobile.'+name,p.locator(sel).count()==1,p.locator(sel).count());ov=p.evaluate('()=>document.documentElement.scrollWidth-innerWidth');ck('mobile.'+name+'.overflow',ov<=2,ov);shot(p,'mobile-'+name+'.png')
with sync_playwright() as pw:
 b=pw.chromium.launch(headless=True);p=b.new_page(viewport={'width':1600,'height':1000});p.on('pageerror',lambda e:R['page_errors'].append(str(e)));p.on('console',lambda m:R['console_errors'].append(m.text) if m.type=='error' else None)
 try:run(p)
 except Exception as e:R['failures'].append({'check':'uncaught','detail':repr(e)})
 b.close()
R['duration_s']=time.time()-R['started_at'];R['ok']=not R['failures'] and not R['page_errors'] and not R['console_errors'];R['count']=len(R['checks']);(OUT/'result.json').write_text(json.dumps(R,ensure_ascii=False,indent=2),encoding='utf-8');print(json.dumps(R,ensure_ascii=False,indent=2));raise SystemExit(0 if R['ok'] else 1)
