/* RT76_BRIDGE_START */
{
  const rt76Ensure=()=>{if(!state)return null;state.rt76||={};const r=state.rt76;r.schema=1;r.scheduledCommands||=[];r.targetIntel||={};r.actionLog||=[];r.market||={minStock:{wood:5000,clay:5000,iron:5000},cycleLimit:3,autoEqualize:false,history:[]};r.market.minStock||={wood:5000,clay:5000,iron:5000};r.market.history||=[];r.farm||={templates:{A:{spear:25},B:{axe:40,light:10},C:{light:40,spy:1}},cycleLimit:5};r.manager||={researchPriority:[],autoScavenge:false,decisionLog:[],lastExtraRun:0};r.manager.researchPriority||=[];r.manager.decisionLog||=[];return r};
  const rt76Log=(type,message,data={})=>{const r=rt76Ensure();if(!r)return;r.actionLog.unshift({id:'rt76_'+Date.now()+'_'+Math.random().toString(36).slice(2,7),type,message,data,at:now()});r.actionLog=r.actionLog.slice(0,250);dirty=true};
  const rt76WithVillage=(id,fn)=>{const prev=state.activeVillageId;state.activeVillageId=String(id);try{return fn()}finally{state.activeVillageId=prev}};
  const rt76Troops=()=>Object.entries(D.units).filter(([,d])=>d.movable!==false).map(([k])=>k);
  const rt76Cap=t=>Object.entries(t||{}).reduce((n,[k,q])=>n+(Number(q)||0)*(Number(D.units[k]?.loot)||0),0);
  const rt76Schedule=({sourceId,targetId,troops,kind='attack',arrivalAt})=>{const r=rt76Ensure(),s=state.villages[String(sourceId)],t=state.villages[String(targetId)];if(!s||s.owner!=='player')throw Error('Origem inválida.');if(!t||t.owner==='player')throw Error('Alvo inválido.');const clean={};let total=0;for(const k of rt76Troops()){const q=Math.max(0,Math.min(s.units[k]||0,Math.floor(Number(troops?.[k])||0)));if(q){clean[k]=q;total+=q}}if(!total)throw Error('Selecione tropas disponíveis.');const travel=travelDuration(s,t,clean),arrive=Number(arrivalAt)||now()+travel,depart=arrive-travel;if(depart<now()+500)throw Error('Horário de chegada cedo demais.');const x={id:'sched_'+Date.now()+'_'+Math.random().toString(36).slice(2,7),sourceId:s.id,targetId:t.id,kind,troops:clean,createdAt:now(),departAt:depart,arrivalAt:arrive,travelDuration:travel,status:'scheduled'};r.scheduledCommands.push(x);r.scheduledCommands.sort((a,b)=>a.departAt-b.departAt);rt76Log('war.schedule','Comando programado',{id:x.id});saveState(true);return x};
  const rt76ProcessScheduled=(ts=now())=>{const r=rt76Ensure();let changed=false;for(const x of r.scheduledCommands){if(x.status!=='scheduled'||x.departAt>ts)continue;const s=state.villages[x.sourceId],t=state.villages[x.targetId];if(!s||!t||!Object.entries(x.troops).every(([k,q])=>(s.units[k]||0)>=q)){x.status='failed';x.error='Origem/alvo/tropas indisponíveis';changed=true;continue}try{rt76WithVillage(s.id,()=>sendAttack(t.id,x.troops,{attackType:x.kind==='farm'?'raid':'normal',rt76ScheduledId:x.id}));x.status='sent';x.sentAt=ts;rt76Log('war.sent','Comando programado enviado',{id:x.id})}catch(e){x.status='failed';x.error=String(e?.message||e)}changed=true}if(changed){dirty=true;saveState(true)}return changed};
  const rt76Cancel=id=>{const x=rt76Ensure().scheduledCommands.find(x=>x.id===id);if(!x||x.status!=='scheduled')return false;x.status='cancelled';x.cancelledAt=now();saveState(true);return true};
  const rt76Recommend=id=>{const x=rt76Ensure().targetIntel[String(id)]||{};if((x.wall||0)>=8)return'B';if(!x.visits)return'A';if((x.fullness||0)>=.9)return'C';if((x.fullness||0)>=.45)return'B';return'A'};
  const rt76Farm=(id,tpl='A')=>{if(!isFarmAssistantActive())throw Error('Ative o Assistente de Saque.');const t=state.villages[String(id)];if(!t||t.owner!=='barbarian')throw Error('Escolha uma aldeia bárbara.');const plan=rt76Ensure().farm.templates[tpl]||{},v=getActiveVillage(),troops={};for(const k of rt76Troops())troops[k]=Math.min(v.units[k]||0,Math.max(0,Math.floor(Number(plan[k])||0)));if(sum(Object.values(troops))<=0)throw Error('Tropas insuficientes.');sendAttack(t.id,troops,{attackType:'raid',rt76FarmTemplate:tpl});rt76Log('farm.send','Farm enviado',{targetId:t.id,template:tpl});return true};
  const RT76_RESOLVE=resolveAttack;resolveAttack=function(c){const s=state?.villages?.[c?.sourceId],t=state?.villages?.[c?.targetId],cap=rt76Cap(c?.troops);const out=RT76_RESOLVE(c);if(s?.owner==='player'&&t?.owner==='barbarian'){const i=rt76Ensure().targetIntel[t.id]||={};const loot=RESOURCE_KEYS.reduce((n,k)=>n+(Number(c?.loot?.[k])||0),0);i.visits=(i.visits||0)+1;i.lastVisit=now();i.lastLoot=loot;i.capacity=cap;i.fullness=cap?Math.min(1,loot/cap):0;i.wall=Number(t.buildings?.wall)||0;i.recommended=rt76Recommend(t.id);dirty=true}return out};
  const rt76MerchantCap=v=>Math.floor(Math.max(1,(v.buildings.market||0)*2)*(hasResearch('trade')?900:650)*(premiumState().tradeLicense?1.35:1)*(1+getTribeTechLevel('logistics')*.05));
  const rt76Equalize=(limit=null)=>{const r=rt76Ensure(),cfg=r.market,owned=Object.values(state.villages).filter(v=>v.owner==='player'&&(v.buildings.market||0)>0),max=Math.max(1,Math.min(20,Number(limit)||Number(cfg.cycleLimit)||3));let sent=0;for(const resource of RESOURCE_KEYS){for(const target of owned.filter(v=>(v.resources[resource]||0)<(cfg.minStock[resource]||0)).sort((a,b)=>a.resources[resource]-b.resources[resource])){if(sent>=max)break;const min=Number(cfg.minStock[resource])||0,donor=owned.filter(v=>v.id!==target.id&&(v.resources[resource]||0)>min+500).sort((a,b)=>b.resources[resource]-a.resources[resource])[0];if(!donor)continue;const amount=Math.min(min-target.resources[resource],donor.resources[resource]-min,rt76MerchantCap(donor));if(amount<100)continue;const fd=new FormData();fd.set('targetId',target.id);RESOURCE_KEYS.forEach(k=>fd.set(k,k===resource?String(Math.floor(amount)):'0'));rt76WithVillage(donor.id,()=>sendResources(fd));cfg.history.unshift({at:now(),sourceId:donor.id,targetId:target.id,resource,amount:Math.floor(amount)});sent++}if(sent>=max)break}cfg.history=cfg.history.slice(0,100);cfg.lastRun=now();if(sent)rt76Log('market.equalize','Equalização por remessas reais',{sent});saveState(true);return sent};
  const RT76_MANAGER=processAccountManager;processAccountManager=function(ts){const changed=RT76_MANAGER(ts),r=rt76Ensure(),cfg=r.manager,p=premiumState();if(isManagerActive()&&p.managerConfig?.enabled&&ts-(cfg.lastExtraRun||0)>=30000){cfg.lastExtraRun=ts;for(const id of cfg.researchPriority){if(!hasResearch(id)&&!state.player.research.queue.some(q=>q.id===id)){const before=state.player.research.queue.length;queueResearch(id);if(state.player.research.queue.length>before){cfg.decisionLog.unshift({at:ts,type:'research',id});break}}}if(cfg.autoScavenge){for(const v of Object.values(state.villages).filter(v=>v.owner==='player')){const sc=ensureScavenging(v);if(sc.unlocked.includes('humble')&&!sc.active.humble){const troop=Object.keys(D.units).find(k=>D.units[k].movable!==false&&!['noble','paladin'].includes(k)&&(v.units[k]||0)>10);if(troop){rt76WithVillage(v.id,()=>{const fd=new FormData();fd.set('option','humble');fd.set('sc_'+troop,String(Math.min(10,v.units[troop]||0)));startScavenge(fd)});cfg.decisionLog.unshift({at:ts,type:'scavenge',villageId:v.id});break}}}}if(r.market.autoEqualize)rt76Equalize(r.market.cycleLimit);cfg.decisionLog=cfg.decisionLog.slice(0,100)}return changed};
  const RT76_MIGRATE=migrateState;migrateState=function(s){const out=RT76_MIGRATE(s);if(s){const old=state;state=s;rt76Ensure();state=old}return out};
  window.RT76={version:'76.1',snapshot:()=>deepClone(rt76Ensure()),state:()=>state,now:()=>now(),scheduleAttack:rt76Schedule,processScheduled:rt76ProcessScheduled,cancelScheduled:rt76Cancel,farmRecommendation:rt76Recommend,farmAttack:rt76Farm,equalizeResources:rt76Equalize,save:()=>saveState(true),setMarketConfig:x=>{Object.assign(rt76Ensure().market,x||{});saveState(true)},setManagerConfig:x=>{Object.assign(rt76Ensure().manager,x||{});saveState(true)},withVillage:rt76WithVillage,sendResources:(sourceId,targetId,p)=>rt76WithVillage(sourceId,()=>{const fd=new FormData();fd.set('targetId',targetId);RESOURCE_KEYS.forEach(k=>fd.set(k,String(p?.[k]||0)));return sendResources(fd)}),test:{getState:()=>state,getActiveVillage:()=>getActiveVillage(),data:()=>D,setView:v=>{currentView=v;modalHtml='';renderAll()},render:()=>renderAll(),save:()=>saveState(true),load:()=>loadState(),updateResources:(v,t)=>updateResources(v,t),queueBuilding:k=>queueBuilding(k),processQueues:t=>processQueues(t),queueRecruit:(k,q)=>queueRecruit(k,q),queueResearch:id=>queueResearch(id),processResearchQueue:t=>processResearchQueue(t),queueUnitResearch:k=>queueUnitResearch(k),processUnitResearch:t=>processUnitResearch(t),sendAttack:(id,t,o)=>sendAttack(id,t,o),processCommands:t=>processCommands(t),processAccountManager:t=>processAccountManager(t),createMarketOffer:f=>createMarketOffer(f),equipHeroItem:id=>equipHeroItem(id),getBuildingVisual:(v,k)=>getBuildingVisual(v,k),heroItems:()=>HERO_ITEMS,getHeroItemArt:id=>getHeroItemArt(id),ensureHeroStoryState:h=>ensureHeroStoryState(h),setAllBuildingTier:t=>{const v=getActiveVillage(),o={};for(const k of Object.keys(D.buildings)){let found=0;for(let lvl=1;lvl<=(D.buildings[k].max||30);lvl++){v.buildings[k]=lvl;if(getBuildingVisual(v,k).tier===t){found=lvl;break}}v.buildings[k]=found||1;o[k]=v.buildings[k]}currentView='overview';renderAll();return o}}};
  if(state)rt76Ensure();window.__RT76_PLAN_APPLIED__=true;
}
/* RT76_BRIDGE_END */